### ISSUE TITLE
Advanced Tomato link not showing on smaller screens

### ISSUE THREAD

**Issue by wrdixon** [ReliefLabs/EasyTomato#25]
We need to add the bootstrap drop down plugin, so we can get back to EasyTomato from advanced tomato.
http://twitter.github.com/bootstrap/javascript.html#dropdowns

**Comment by fougner** [comment]
We should have a common head-header for common javascript, css, etc so we easily can include stuff like that, instead of changing one row in 75 files.

**Comment by fougner** [comment]
Fixed!
