### ISSUE TITLE
Can't Update Tomato Version from Advanced Tomato!

### ISSUE THREAD

**Issue by wrdixon** [ReliefLabs/EasyTomato#29]
The Upgrade doesn't work on Advanced Tomato (worked before we merged into EasyTomato).  The screen shows up and prompts you "Are you sure you want to" then it just goes blank.  The router isn't flashed.

Have to use recovery mode now to get new version on.

**Comment by fougner** [comment]
This is easily fixed.

Btw, I have a new fancy modal popup dialog with a progressbar for the flashing progress, do you want a preview?

**Comment by wrdixon** [comment]
Hell yeah :)!  Are you testing these in your branch and are then going to merge them into the main EasyTomato branch?

**Comment by fougner** [comment]
Yeah,

It's fancy, but not really necessary.

And no, I will not push experimental stuff like that to the public branch.
