### ISSUE TITLE
Changing Routers IP address Breaks iptables

### ISSUE THREAD

**Issue by wrdixon** [ReliefLabs/EasyTomato#34]
If access control rules exist and the IP address of the router is changed, iptables breaks.  Restarting the router will fix the problem.

Something broken in ipt_account which stops iptables rules being loaded and all the functions that use these.

Sep 29 13:02:42 unknown user.err kernel: ipt_account [checkentry]: table found, rule network/netmask/shortlisting not match table network/netmask/shortlisting.
Sep 29 13:02:42 unknown user.crit dhcpc-event[2528]: Error while loading rules. See /etc/iptables.error file.
Sep 29 13:02:43 unknown user.err kernel: ipt_account [checkentry]: table found, rule network/netmask/shortlisting not match table network/netmask/shortlisting.
Sep 29 13:02:43 unknown user.crit init[1]: Error while loading rules. See /etc/iptables.error file.
Sep 29 13:02:44 unknown user.err kernel: ipt_account [checkentry]: table found, rule network/netmask/shortlisting not match table network/netmask/shortlisting.

**Comment by wrdixon** [comment]
Fixed with some changes to cstats.

**Comment by wrdixon** [comment]
https://github.com/ReliefLabs/EasyTomato/commit/683489535968a74fdeb64776e1ad904bfedfca45

**Comment by RMerl** [comment]
This looks similar to the issue I have been working on for the past couple of days, except I thought it was specific to the 2.6.36 kernel I was using in this case (it also happen on my 3.2.0 Ubuntu box).  I found where the userspace tool fails, but cannot figure out yet the reason.
