### ISSUE TITLE
Narrow Port Range for HTTPS Block

### ISSUE THREAD

**Issue by wrdixon** [ReliefLabs/EasyTomato#45]
Right now its 1-600.  We likely only need to be looking on 53 and 80.

**Comment by djfurie** [comment]
I think that rule refers to bytes to search (search the first 600 bytes for the string).  I agree that we should limit the port range though; I think we're actually searching _all_ packets going through (got to confirm that though).  We may need to rearrange how all the iptables chains are setup.  Almost recovered from jetlag, should have time to look into this later in the week.

**Comment by wrdixon** [comment]
Yeah, I figured as much after reading some iptables docs a few days ago (post posting this).  I'm almost done too.  Slept in until 6:30am today!
