### ISSUE TITLE
Set EasyTomato to clear NV on update

### ISSUE THREAD

**Issue by wrdixon** [ReliefLabs/EasyTomato#48]
Figure out a way to clear the old NVram and maybe tell the users what we're resetting (likely only going to work for ET to ET updates.  We can update the user guide to tell everyone to write stuff down/take screen shots too.

It shouldn't be too hard to figure out if an NV clear is necessary, as you were saying.  We can look into that too, which would make minor ET updates easier.

**Comment by djfurie** [comment]
https://github.com/ReliefLabs/EasyTomato/commit/12647afd7a254ff7f9b754f7014031b301ca71ca

Won't close this issue until we've tested this a bit more.  Also need to give more thought to how to alert users that this is happening to them and potentially give them a last chance to save off custom settings.
