### ISSUE TITLE
Access Restriction rules created in "Advanced" get deleted after any rule change in "Basic" mode.

### ISSUE THREAD

**Issue by EagleEye905** [ReliefLabs/EasyTomato#55]
ET team, 

You have a fabulous ET interface!  I did notice that any Access Restriction rule that gets created in the AdvancedTomato mode (AT mode), will get deleted if any rule changes are made in EasyTomato (ET) mode.

I'm using version 0.8

Steps to reproduce:
1. Go to AT mode.
2. Create a rule. Name it AT-Rule100    (or any name)
3. Go to ET mode
4. Add a new rule, and call it EasyRule200
5. Go back to AT mode
6. You will notice that in the Access Restrictions screen, AT-Rule100 no longer exists.

I can reproduce this scenario consistently and every time.

Cheers,

**Comment by wrdixon** [comment]
The rules from ET overwrite anything you do in AdvancedTomato, so this is expected behavior. 

We could always just remove the page for Access Restrictions from AT or put a warning sign on it.
