### ISSUE TITLE
Native support for DNSCrypt

### ISSUE THREAD

**Issue by kamushadenes** [ReliefLabs/EasyTomato#60]
Hello guys,

Is there any plans to support, in the near future, OpenDNS' DNSCrypt feature? Several dns servers are starting to support it and it would look like it is coming to be a industry standard.

More info:
http://dnscrypt.org/
http://www.opendns.com/about/innovations/dnscrypt/

Thanks!

**Comment by lancethepants** [comment]
Other mods (ie, shibby, raf) already have DNSCrypt integrated.  Toastman's branch, from which EasyTomato is based does not, and Toastman has spoken his disdain for adding it. I've done some modifying of DNSCrypt available in the shibby and raf mods, and would be willing to add support here if the devs confirm they would include it.  Not sure about the easytomato interface, but in the traditional one anyway.
