### ISSUE TITLE
EasyTomato is using a verion of OpenSSL between 1.0.1 and 1.0.1f or was not builting with OPENSSL_NO_HEARTBEATS

### ISSUE THREAD

**Issue by derekschrock** [ReliefLabs/EasyTomato#61]
http://heartbleed.com/

EasyTomato is using a version (1.0.1c) of OpenSSL between 1.0.1 and 1.0.1f or was not built with OPENSSL_NO_HEARTBEATS.

Anything using openssl heartbeast should be problematic (openvpn)

OpenSSL needs upgraded to 1.0.1g or downgraded to <1.0.1

**Comment by djfurie** [comment]
Resolved in 6058ac3ce7348a6bebf5d62e5552ad0f17c590ea

**Comment by dalin-** [comment]
Does this mean that the current version is vulnerable to hearbleed?

**Comment by fougner** [comment]
@dalin- If you're using the web interface with HTTPS or using OpenVPN, then as far as I know it is vulnerable.

**Comment by beaylott** [comment]
I think you are doing amazing stuff and I really like what you have done with Tomato...but you _really_ need to do a point release with a build with this fix.
