### ISSUE TITLE
Address recent security issues by releasing new compiled version.

### ISSUE THREAD

**Issue by frob** [ReliefLabs/EasyTomato#65]
The two largest ones that come to mind are the Heartbleed bug and the Shellshock bug. 

Is there any easy way to patch these security issues? Are they security issues on tomato?

**Comment by fougner** [comment]
Heartbleed is fixed in openssl 1.0.1g, which is the latest commit in our repo.
Tomato doesn't use Bash, thus not affected by Shellschock.

**Comment by frob** [comment]
That doesn't make sense. The current version for download on the site has a release date of 10 June 2013. OpenSSL 1.0.1g has a release date of Oct 15 2014.

**Comment by fougner** [comment]
@frob No one has compiled and released a new version, but the fixes are in the repo if you want to compile it yourself.

**Comment by frob** [comment]
I updated the title of the issue to reflect what the issue really is.
